-
  name: 'Default'
  uriPattern:    ''
  defaults:
    '@package':    'Fernando.Docs'
    '@controller': 'Documento'
    '@action':     'index'
    '@format':     'html'

-
  name: 'documentos'
  uriPattern:    'docs/{@controller}/{@action}(/index.{@format})'
  defaults:
    '@package':    'Fernando.Docs'
    '@controller': 'Documento'
    '@action':     'index'
    '@format':     'html'
    