FLOW3:
  security:
    authentication:
      authenticationStrategy: oneToken
      providers:
        DefaultProvider:
          providerClass: PersistedUsernamePasswordProvider
          entryPoint:
            WebRedirect:
              uri: login/index